# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.6.0.schema.json

PackageIdentifier: TonyTheThompson.Numan
PackageVersion: 0.1.2
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
Installers:
  - Architecture: x64
    InstallerType: zip
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: numan-0.1.2-x86_64-pc-windows-msvc\numan.exe
        PortableCommandAlias: numan
    InstallerUrl: https://github.com/tonythethompson/numan/releases/download/v0.1.2/numan-0.1.2-x86_64-pc-windows-msvc.zip
    InstallerSha256: AB10CF0902EB62D2317D937D2C34ECAA59CF8C0F5D787A7D35C355A07ECF7253
    UpgradeBehavior: uninstallPrevious
